//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorAppointment_New.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int booking_id { get; set; }
        public int tutor_id { get; set; }
        public int student_id { get; set; }
        public string notes { get; set; }
        public int status_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public int subject_id { get; set; }
    
        public virtual status status { get; set; }
        public virtual student student { get; set; }
        public virtual tutor tutor { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
