//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorAppointment_New.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TutorAppointmentEntities : DbContext
    {
        public TutorAppointmentEntities()
            : base("name=TutorAppointmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<booking> booking { get; set; }
        public DbSet<favorites> favorites { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<status> status { get; set; }
        public DbSet<student> student { get; set; }
        public DbSet<Subjects> Subjects { get; set; }
        public DbSet<subjectsTutor> subjectsTutor { get; set; }
        public DbSet<tutor> tutor { get; set; }
    }
}
