//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorAppointment_New.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.booking = new HashSet<booking>();
            this.favorites = new HashSet<favorites>();
        }
    
        public int student_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string fio { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string grade { get; set; }
    
        public virtual ICollection<booking> booking { get; set; }
        public virtual ICollection<favorites> favorites { get; set; }
    }
}
