//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorAppointment_New.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public Subjects()
        {
            this.subjectsTutor = new HashSet<subjectsTutor>();
            this.booking = new HashSet<booking>();
        }
    
        public int subjects_id { get; set; }
        public string subject_name { get; set; }
    
        public virtual ICollection<subjectsTutor> subjectsTutor { get; set; }
        public virtual ICollection<booking> booking { get; set; }
    }
}
