//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorAppointment_New.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjectsTutor
    {
        public int subjectTutor_id { get; set; }
        public int tutor_id { get; set; }
        public int subject_id { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual tutor tutor { get; set; }
    }
}
