//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorAppointment_New.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tutor
    {
        public tutor()
        {
            this.booking = new HashSet<booking>();
            this.favorites = new HashSet<favorites>();
            this.subjectsTutor = new HashSet<subjectsTutor>();
        }
    
        public int tutor_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
        public string fio { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string raiting { get; set; }
        public string info { get; set; }
    
        public virtual ICollection<booking> booking { get; set; }
        public virtual ICollection<favorites> favorites { get; set; }
        public virtual role role { get; set; }
        public virtual ICollection<subjectsTutor> subjectsTutor { get; set; }
    }
}
